apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videos-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: health-ai-assets-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}